### ISSUE TITLE
XMLHttpRequest cannot load, No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin

### ISSUE THREAD

**Issue by cristhianCMH** [GeekyTheory/Automatic-API-REST#10]
Hola estoy tratando de hacer una app mobil con el framework ionic para app hibridas, cuando quiero usar este proyecto para el consumo del api, me sale este error, en que archivo se deben colocar estos coords para que me permita acceder a ese link, saludos

**Comment by gurumelo** [comment]
Hola, si usas apache

http://enable-cors.org/server_apache.html

si usas nginx

add_header Access-Control-Allow-Origin *;

2016-03-26 22:52 GMT+01:00 Cristhian Molina notifications@github.com:

**Comment by cristhianCMH** [comment]
Hola acabo de solucionarlo para apache, colocando estas lineas de código en el archivo api.php, después del require_once

`header('Access-Control-Allow-Origin: *');`

`header("Access-Control-Allow-Headers: X-API-KEY, Origin, X-Requested-With, Content-Type, Accept, Access-Control-Request-Method");`

`header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");`

**Comment by gurumelo** [comment]
Perfecto, gracias por publicar la solución

2016-04-03 17:59 GMT+02:00 Cristhian Molina notifications@github.com:
