### ISSUE TITLE
why its so?

### ISSUE THREAD

**Issue by shajal16** [GeekyTheory/Automatic-API-REST#15]
| Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in C:\xampp\htdocs\auto\mod\modTable.php on line 32
-- | --
and xaml view giving this error
{"errors":[{"code":301,"message":"Invalid Parameters: "}]}

**Comment by tri16cc** [comment]
I've the same problem, Could you fix it?

**Comment by shajal16** [comment]
no did you ? what ever database i use. there's always a table with this. {"errors":[{"code":301,"message":"Invalid Parameters: "}]}

**Comment by shajal16** [comment]
@alejandroesquiva please can you help

**Comment by tri16cc** [comment]
No, but I found a solution modifying the url related with my database and worked. But the api don't do automatic, I need to put my url. And I can't find the problem... but I hope that if you try modifying your url could help you too. If you need more help or information text me and I'll try to help you

**Comment by shajal16** [comment]
@tri16cc  can you tell me what you did there i mean how?

**Comment by tri16cc** [comment]
when you click on any table you see all the columns of your database, if you select some different attributes you see down a table to make your query. If you click on "show JSON tree" appears the error but if you copy the url that you see on this table for example "http://localhost/api/get/employees/id_employee/" and you copy in a new window on your browser you'll see the JSON tree. This works for me. I don't know what it's happening for not working automatic, but... at least, I hope that you can work with this. Write me if works for you.
