### ISSUE TITLE
Warning: SimpleXMLElement::__construct(): I/O warning : failed to load external entity &quot;xml/blacklist.xml&quot; in C:\wamp\www\Automatic-API-REST\inc\blackListClass.php on line 97

### ISSUE THREAD

**Issue by Fshamri** [GeekyTheory/Automatic-API-REST#6]
i got those errors after installation:
Warning: SimpleXMLElement::__construct(): I/O warning : failed to load external entity &quot;xml/blacklist.xml&quot; in C:\wamp\www\Automatic-API-REST\inc\blackListClass.php on line 97

Fatal error: Uncaught exception 'Exception' with message 'String could not be parsed as XML' in C:\wamp\www\Automatic-API-REST\inc\blackListClass.php on line 97
( ! ) Exception: String could not be parsed as XML in C:\wamp\www\Automatic-API-REST\inc\blackListClass.php on line 97

**Comment by alejandroesquiva** [comment]
Hi, try to modify the permissions of the file xml/blacklist.xml in order to become the file readable.

Best Regards

**Comment by Fshamri** [comment]
it works ....... thanks for your help.
other question, how can i use your tool for sqlite database?

**Comment by alejandroesquiva** [comment]
Right now it is just implemented for mysql, but i have in mind extend the tool, and include others data bases. 

Regards
